app/apaxhr/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views

import os
admin.site.site_header = "APAX Admin"
admin.site.site_title = "APAX Admin Portal"
admin.site.index_title = "APAX HR administrator Portal"

app_name='apaxhr'
# path('employee_management/', include('employee_management.urls')),
urlpatterns = [
    path('', views.HomePage.as_view(),name='home_simple'),
    path('logout/', views.logout_view, name='logout'),
    # path('home/', views.HomePage.as_view(), name='home'),
    path('home/<access_tier>', views.HomePage.as_view(), name='home'),


    path('core_hr/', include('core_hr.urls')),
    path('users/', include('users.urls')),
    path('employee_mgmt/', include('employee_mgmt.urls')),
    path('employment/', include('employment.urls')),
    path('centers/', include('centers.urls')),


    # auth routes
    # path('login/', auth_views.auth_login),
    # path('logout/', auth_views.auth_logout),
    path('admin/', admin.site.urls),

]

# path('employee_management/', include('employee_management.urls')),

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),


if not settings.USE_S3:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core_hr/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'core_hr'

urlpatterns = [
    path('', views.CoreHrHome.as_view(), name='self_service'),
    path('documents/', views.DocumentCenter.as_view(), name='document_center'),

    path('documents/passport/view/', views.PassportView.as_view(), name='passport_view'),
    path('documents/passport/update/', views.PassportUpdateCreate.as_view(), name='passport_update'),

    path('documents/ros/view/', views.RosView.as_view(), name='ros_view'),
    path('documents/ros/update/', views.ROSUpdateCreate.as_view(), name='ros_update'),

    path('documents/workpermit/view/', views.WorkPermitView.as_view(), name='work_permit_view'),
    path('documents/workpermit/update/', views.WorkPermitUpdateCreate.as_view(), name='work_permit_update'),

    path('documents/resume/view/', views.ResumeView.as_view(), name='resume_view'),
    path('documents/resume/update/', views.ResumeUpdateCreate.as_view(), name='resume_update'),

    path('documents/certificate/view/', views.TeachingCertificateView.as_view(), name='teach_certificate_view'),
    path('documents/certificate/update/', views.TeachingCertificateUpdateCreate.as_view(), name='teach_certificate_update'),

    path('documents/degree/view/', views.DegreeView.as_view(), name='degree_view'),
    path('documents/degree/update/', views.DegreeUpdateCreate.as_view(), name='degree_update'),

    path('documents/achcert/view/', views.AchievementCertificateView.as_view(), name='ach_cert_view')

]

app/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views



app_name = 'users'

urlpatterns = [
    path('', views.UsersHome.as_view(), name='homepage'),
    path('registration/', views.UserCreateView.as_view(), name='registration'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('update/', views.UserUpdateView.as_view(), name='employee_update'),
]

app/templates/header_footer/footer.html
<footer>
    {#    Material design cdn#}
    {#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-kit/2.0.6/css/material-kit.css.map">#}
    {#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-kit/2.0.6/css/material-kit.css" >#}
    {#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-kit/2.0.6/js/material-kit.js" >#}

    {#    <link rel="stylesheet" href="{% static "/css/bootstrap.css" %}">#}
    {##}
    {#    <link rel="stylesheet" href="{% static "/css/bootstrap-reboot.css" %}">#}
    {##}
    {#    <link rel="stylesheet" href="{% static "/css/bootstrap-grid.css" %}">#}
    {##}
    {#    <link rel="stylesheet" href="{% static "/js/bootstrap.bundle.js" %}">#}
    {##}
    {#    <link rel="stylesheet" href="{% static "/js/bootstrap.js" %}">#}
    {##}


    {% load static %}
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">


{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"#}
{#          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">#}
{##}
{#    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">#}

{#    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"#}
{#            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"#}
{#            crossorigin="anonymous"></script>#}
{#    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"#}
{#            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"#}
{#            crossorigin="anonymous"></script>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"#}
{#            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"#}
{#            crossorigin="anonymous"></script>#}


        <style>
        .blinking {
            animation: blinkingText 2s infinite;
        }

        @keyframes blinkingText {
            0% {
                color: #000;
            }
            49% {
                color: #000;
            }
            60% {
                color: transparent;
            }
            99% {
                color: transparent;
            }
            100% {
                color: #000;
            }
        }

    </style>

</footer>

app/templates/header_footer/nav.html
{% load static %}
<nav class="navbar navbar-light navbar-expand-lg bg-danger sticky-top ">
    <div class="container">
        <a class="navbar-brand text-white" href="{% url 'home_simple' %}"><h4>APAX HR</h4></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"> </span>
        </button>

        <div class="collapse navbar-collapse container" id="navbarResponsive">
            <ul class="nav navbar-nav ml-auto">


                {% if request.session.tier1  or request.session.tier2 or request.session.tier3 or request.session.tier4 %}
                    <li class="nav-item">
                        <a class="nav-link btn text-white" href="{% url 'core_hr:self_service' %}">Employee Portal</a>
                    </li>
                {% endif %}

                {% if request.session.tier2 or request.session.tier3 or request.session.tier4 %}
                    <li class="nav-item">
                        <a class="nav-link btn text-white" href="#">Center Tools</a>
                    </li>
                {% endif %}

                {% if request.session.tier2 or request.session.tier3 or request.session.tier4 %}
                    <li class="nav-item">
                        <a class="nav-link btn text-white" href="#">Teacher Management</a>
                    </li>
                {% endif %}

                {% if request.session.tier3 or request.session.tier4 %}
                    <li class="nav-item">
                        <a class="nav-link btn text-white" href="#">HR Tools</a>
                    </li>
                {% endif %}
                {% if request.session.tier3 or request.session.tier4 %}
                    <li class="nav-item">
                        <a class="nav-link btn text-white" href="#">Payroll</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link btn text-white" href="{% url 'users:user_login' %}">Login</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link btn text-white" href="{% url 'users:registration' %}">Signup</a>
                </li>


            </ul>
        </div>
    </div>
</nav>